# manual trigger -11
sendErrorOptIn:  true
jobs:
  download-dev:
    target:
        adx:
            clusterUri:  to-be-overriden
            database:  dtnadev01
    action:
        filePath:  kql-scripts/dev-state.kql
        
  download-prod:
    target:
        adx:
            clusterUri:  to-be-overriden
            database:  dtnaadxprod01
    action:
        filePath:  kql-scripts/prod-state.kql
        
        
  delta-dev:
    current:
        adx:
            clusterUri:  to-be-overriden
            database:  dtnaadxprod01
        
    target:
     
         adx:
            clusterUri:  to-be-overriden
            database:  dtnadev01
#        scripts:
#         - filePath:  ../deploy_delta_to_prod/state/target_state.kql
        
    action:
        pushToConsole:  true
        filePath:  kql-scripts/delta.kql
tokenProvider:
    login:
        tenantId:  to-be-overriden
        clientId:  to-be-overriden
        secret:  to-be-overriden
