name: Workflow to deploy ADF ARM Template to UAT environment from DEV environment
on: 
  push:
    branches: 
      - main
    paths:
      - scripts/**

env:

  CLUSTER_URI: ${{ secrets.cluster_uri }}
  TENANT_ID: ${{ secrets.tenant_id }}
  CLIENT_ID: ${{ secrets.client_id }}
  SECRET: ${{ secrets.secret_value }}
  

jobs:
  Generate_delta_for_devdb:
      
    runs-on: ubuntu-latest
    steps:
    # Authentication 

    - name: run the bash script to install delta kusto CLI
      run: |

        wget https://github.com/microsoft/delta-kusto/releases/download/0.6.0.85/delta-kusto-linux.tar.gz
        tar --extract --file delta-kusto-linux.tar.gz
        chmod +x ./delta-kusto 
        cp delta-kusto /bin 
    
    # Checkout
    - name: Checkout
      uses: actions/checkout@v1 
      
    - name: prepare the script folders
      run: |

        mkdir scripts/kql-scripts
        mkdir scripts/kql-scripts/complete
    
    - name: run delta kusto 
      run: |
        clusterUri=$(CLUSTER_URI)
        echo "Cluster URI:  $clusterUri"
        # Package the login in a JSON payload
        login='{"tenantId":"$(TENANT_ID)","clientId":"$(CLIENT_ID)","secret":"$(SECRET)"}'
        ./delta-kusto -p documentation/tutorials/az-dev-ops/reverse-engineer/rev-engineer-parameters.yaml -o jobs.download-dev.target.adx.clusterUri=$clusterUri jobs.delta-dev.target.adx.clusterUri=$clusterUri tokenProvider.login=$login
      
    
    # artifacts upload
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: published
        path: scripts/kql-scripts
